import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;
import javax.swing.JFileChooser;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kushal Gurung 18029022
 * @author Sanjit Adhikari 18029085
 * @author Sadikshya Baral 18029069
 * @author Hrithik Sunar 18029017
 * @author Sagar Nepali 18029075
 */
public class CAD_Info extends javax.swing.JFrame
{
    DefaultTableModel model;
    ArrayList<Object> idNumberArrayList = new ArrayList<>();
    //Constructor method
    public CAD_Info() 
    {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        //multi dimensional array
        Object[][] array = 
        {
            {1, "Comfort", "Armrest", "AR01", "Low", "735", "Company, Community"},
            {2, "Comfort", "Blind spot mirrors", "BSM02", "Low", "388", "No Recommendation"},
            {3, "Comfort", "Sun reflector", "SR03", "Low", "344", "Company"},
            {4, "Body Kit", "Spoilers", "S04", "Medium", "3000", "Community"},
            {5, "Body Kit", "Bumper Lips", "BL05", "Low", "1450", "No Recommendation"},
            {6, "Body Kit", "Roof Scoops", "RS06", "High", "5800", "Company"},
            {7, "Media", "In-Dash DVD/CD Monitor", "IDCM07", "High", "7000", "Community"},
            {8, "Media", "Rearview Backup Camera", "RBC08", "Low", "1900", "Company"},
            {9, "Media", "Rearview Mirror Monitor", "RMM09", "High", "5000", "Community"},
            {10, "Sensors", "Airbag sensors", "AS10", "High", "6500", "Company"},
            {11, "Sensors", "Coolant temperature sensor", "CTS11", "Low", "1950", "Company"},
            {12, "Sensors", "Fuel level sensor", "FLS12", "High", "1450", "Company"},
            {13, "Gauge & meters", "Fuel Gauge", "FG13", "Low", "800", "No Recommendation"},
            {14, "Gauge & meters", "Speedometer", "S14", "Low", "1000", "Company, Community"},
            {15, "Gauge & meters", "Odometer", "O15", "Low", "800", "Company"}
        };
        
        //Addition of object data type values in array.
        for (Object [] rowValues : array)
        {
            model.addRow(rowValues);
            idNumberArrayList.add(rowValues);
        }
        
        //Creation of a titled border and setting the border into a panel.
        jPanel1.setBorder(BorderFactory.createTitledBorder
        (
                BorderFactory.createEtchedBorder(), "Car Accessories Details" , TitledBorder.CENTER, TitledBorder.TOP)
        );
        //Setting white font color of titled border. 
        TitledBorder titledBorder = (TitledBorder)jPanel1.getBorder();
        titledBorder.setTitleColor(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      public void sort(int [] a)
      {        
      // This method will sort the value of an array which is passed as an argument in this method's parameter.
	for(int i=0;i<a.length;i++)
        {
	int minVal = minimumValue(a,i);
	swap(a,minVal,i);	
        }
      }

    public int minimumValue(int [] a, int form)
    {
     //This method finds the minimum value by comparing one number with another.
	int minVal = form;
	for(int i = form +1;i<a.length;i++)
        {
            if(a[i]<a[minVal])
            {
		minVal = i;
            }
	}
        return minVal;		
    }
    
    public void swap(int [] a,int i,int j)
    {
    //This method will swap the position of smaller and greater number. It keeps smaller number at first.
	int temp= a[i];
	a[i] = a[j];
	a[j] = temp;
    }
    
    
    public int binarySearch(int [] a, int key) 
    {
    //This is a binary search method which will be called later while searching for accessories through price.
       sort(a);
       int size = a.length;
       int low = 0;
       int high = size-1;
       while (low <= high) 
       {
            int mid = (low + high) / 2;
            if (a[mid] == key) 
            {
                return a[mid];
            }
            else if (key > a[mid]) 
            {
                low = mid + 1;
            } 
            else 
            {
                high = mid - 1;
            }
        }
        return -1;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        accessoriesNameTextField = new javax.swing.JTextField();
        accessoriesNumberTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        companyCheckBox = new javax.swing.JCheckBox();
        communityCheckBox = new javax.swing.JCheckBox();
        noRecommendationCheckBox = new javax.swing.JCheckBox();
        addButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lowRadioButton = new javax.swing.JRadioButton();
        mediumRadioButton = new javax.swing.JRadioButton();
        highRadioButton = new javax.swing.JRadioButton();
        priceTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        priceSearchTextField = new javax.swing.JTextField();
        priceSearchButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        categorySearchButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        priceSearchClearButton = new javax.swing.JButton();
        clearSelectedButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        exitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        viewHelpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Accessories Information System");

        jPanel5.setBackground(new java.awt.Color(43, 81, 95));

        jPanel2.setBackground(new java.awt.Color(0, 140, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(47, 79, 79), 1, true));
        jPanel2.setForeground(new java.awt.Color(215, 215, 215));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Accessories Details");

        accessoriesNameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accessoriesNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accessoriesNameTextFieldKeyTyped(evt);
            }
        });

        accessoriesNumberTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accessoriesNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessoriesNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Recommendation");

        companyCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        companyCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        companyCheckBox.setText("Company");
        companyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyCheckBoxActionPerformed(evt);
            }
        });

        communityCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        communityCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        communityCheckBox.setText("Community");
        communityCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityCheckBoxActionPerformed(evt);
            }
        });

        noRecommendationCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        noRecommendationCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        noRecommendationCheckBox.setText("No Recommendation");
        noRecommendationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRecommendationCheckBoxActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comfort", "Body Kit", "Media", "Sensors", "Gauge and meters" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Accessories Name");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Range Level");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Accessories Number");

        buttonGroup1.add(lowRadioButton);
        lowRadioButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lowRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        lowRadioButton.setText("Low");
        lowRadioButton.setFocusCycleRoot(true);
        lowRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mediumRadioButton);
        mediumRadioButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mediumRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        mediumRadioButton.setText("Medium");
        mediumRadioButton.setFocusCycleRoot(true);

        buttonGroup1.add(highRadioButton);
        highRadioButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        highRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        highRadioButton.setText("High");
        highRadioButton.setFocusCycleRoot(true);

        priceTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category");

        clearButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(accessoriesNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(accessoriesNumberTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lowRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mediumRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(highRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(communityCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(companyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(noRecommendationCheckBox)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accessoriesNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accessoriesNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowRadioButton)
                    .addComponent(mediumRadioButton)
                    .addComponent(highRadioButton))
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityCheckBox)
                    .addComponent(companyCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noRecommendationCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel3.setBackground(new java.awt.Color(0, 140, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Accessories Information System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 140, 153));

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category", " Name", " Number", "Range Level", "Price ", "Recommendation"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(1).setMinWidth(130);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(130);
            jTable1.getColumnModel().getColumn(2).setMinWidth(200);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(300);
            jTable1.getColumnModel().getColumn(3).setMinWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(4).setMinWidth(90);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMinWidth(80);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(6).setMinWidth(150);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(170);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 140, 153));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price");

        priceSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSearchTextFieldActionPerformed(evt);
            }
        });

        priceSearchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceSearchButton.setText("Search");
        priceSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSearchButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Category");

        categoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comfort", "Body Kit", "Media", "Sensors", "Gauge and meters" }));

        categorySearchButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        categorySearchButton.setText("Search Category");
        categorySearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorySearchButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Clear Details From Table");

        priceSearchClearButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceSearchClearButton.setText("Clear");
        priceSearchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSearchClearButtonActionPerformed(evt);
            }
        });

        clearSelectedButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clearSelectedButton.setText("Clear Selected");
        clearSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSelectedButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Search From Price");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Search From Category");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Exit the System");

        exitButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(categorySearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(jSeparator4)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(priceSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(priceSearchClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(priceSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jSeparator5)
                                .addComponent(clearSelectedButton))
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceSearchClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categorySearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearSelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        fileMenu.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        viewHelpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        viewHelpMenuItem.setText("View Help");
        viewHelpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHelpMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(viewHelpMenuItem);

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void communityCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityCheckBoxActionPerformed
        // TODO add your handling code here:
        //When community check box is selected, no recommendation button will be set to false.
        noRecommendationCheckBox.setSelected(false);
    }//GEN-LAST:event_communityCheckBoxActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
            this.dispose(); //closes the information system application.
    }//GEN-LAST:event_exitButtonActionPerformed

    private void lowRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowRadioButtonActionPerformed

    //This method will add items in the table.
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String range = "";
        String recommendation = "";
        String category = jComboBox1.getSelectedItem().toString();
        String accessoriesName = accessoriesNameTextField.getText();
        String accessoriesNumber = accessoriesNumberTextField.getText();
        String price = priceTextField.getText();
        
        if (lowRadioButton.isSelected()) 
        {
            range = lowRadioButton.getText().toString();
        }
        if (mediumRadioButton.isSelected()) 
        {
            range = mediumRadioButton.getText().toString();
        }
        if (highRadioButton.isSelected()) 
        {
            range = highRadioButton.getText().toString();
        }
        if (companyCheckBox.isSelected()) 
        {
            recommendation = String.valueOf("Company");
        }
        if (communityCheckBox.isSelected()) 
        {
            recommendation = String.valueOf("Community");
        }
        if (noRecommendationCheckBox.isSelected()) 
        {
            recommendation = String.valueOf("No Recommendation");
        }
        if (companyCheckBox.isSelected() && communityCheckBox.isSelected())
        {
            recommendation = String.valueOf("Company, Community");
        }
        try
        {
            if(accessoriesNumber.equals("") && accessoriesName.equals("") && range.equals("") && price.equals("") && recommendation.equals("")) 
            {
                 Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please enter all the value.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if(accessoriesNumber.equals("")) 
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please enter the accessories number.", "Error!", JOptionPane.ERROR_MESSAGE);
            }      
            else if(accessoriesName.equals("")) 
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please enter the accessories name.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if (category.equals(""))
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please select a accessories category.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if(range.equals(""))
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please select a accessories prize range.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if(price.equals("")) 
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please enter the accessories price.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if(Integer.parseInt(price)<0)
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please enter the correct accessories price.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if(recommendation.equals("")) 
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please select the accessories recommendations.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else
            {  //else condition will run when all the values are added and selected in text fields, combox boxes and radio buttons.
                int id = idNumberArrayList.size()+1;   //It stores the id number which will be added by 1, every time a new accessory is added.
                String idNumber = String.valueOf(id);
                String [] arrayAdd = {idNumber, category, accessoriesName, accessoriesNumber, range, price, recommendation};
                model.addRow(arrayAdd);
                idNumberArrayList.add(arrayAdd);
                JOptionPane.showMessageDialog(this, "Accessory is successfully added.", "Result", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(NumberFormatException exceptionVariable) {
            Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Please enter correct value in price", "Error!", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_addButtonActionPerformed

    private void noRecommendationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRecommendationCheckBoxActionPerformed
        // TODO add your handling code here:
        //When no recommendation check box is selected, company and community check box will be set to false.
        companyCheckBox.setSelected(false);
        communityCheckBox.setSelected(false);
    }//GEN-LAST:event_noRecommendationCheckBoxActionPerformed

    private void companyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyCheckBoxActionPerformed
        // TODO add your handling code here:
        //When company check box is selected, no recommendation check box is set to false.
        noRecommendationCheckBox.setSelected(false);
    }//GEN-LAST:event_companyCheckBoxActionPerformed

    private void priceSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceSearchTextFieldActionPerformed

    private void priceSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSearchButtonActionPerformed
        // TODO add your handling code here
        //Search by price:
        try
        {
        int rowCount = jTable1.getRowCount();
        String search = priceSearchTextField.getText();
        if(!"".equals(search) && rowCount!=0) 
        {
            int searchItem = Integer.parseInt(priceSearchTextField.getText());  //The value that we enter in the price search text field.
            int data[] = new int[rowCount];
            for(int i=0; i<rowCount; i++) 
            {
                data [i] = Integer.parseInt(jTable1.getValueAt(i, 5).toString());  //Since our price is on 5th position, data [i] will get the value of 5th position.
            }
            int searchResult = binarySearch(data, searchItem);    //binary search method is called.
            if (searchResult != -1) 
            {
                for (int i = 0; i < rowCount; i++) 
                {
                    if (Integer.parseInt(jTable1.getValueAt(i, 5).toString()) == searchResult) 
                    {
                        int itemIndex = 2;
                        String itemName = jTable1.getValueAt(i, itemIndex).toString();  //Our accessories name is stored at 2nd position, itemIndex value is assigned with 2.
                        JOptionPane.showMessageDialog(this, "Search Found!\nPrice: Rs." + searchItem + "\nAccessories: " + itemName, "Result", JOptionPane.INFORMATION_MESSAGE);
                        break;                  
                    }
                }
            } 
            else 
            {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No accessories are available for this price.", "Result", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else 
        {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Please enter price.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        }
        catch(NumberFormatException exception) 
        {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Please enter price amount in whole number.","Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_priceSearchButtonActionPerformed

     
    private void categorySearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorySearchButtonActionPerformed
        // TODO add your handling code here:
        //search by category.
        String categoryItems = categoryComboBox.getSelectedItem().toString();
        int searchIndex1 = 1;
        int rows1 = jTable1.getRowCount();
        int no = 1;
        String displayName="";
        for (int i = 0; i < rows1; i++) 
        {
            if ((jTable1.getValueAt(i, searchIndex1).toString()).equals(categoryItems))
            { 
            //searchIndex1 is assigned with 1 since our category is at 1st position of the array.
                int itemIndex = 2;
                displayName = displayName+ no + "." + ((String) jTable1.getValueAt(i, itemIndex)) + "\n";
                no++;
            }
        }
        if (!"".equals(displayName))
        {
            JOptionPane.showMessageDialog(this, displayName, (no-1) + " accessories found in " + categoryItems+" category.", JOptionPane.INFORMATION_MESSAGE);
        } 
        else 
        {
            JOptionPane.showMessageDialog(this, "No Items Related to Category: " + categoryItems, "Message", JOptionPane.INFORMATION_MESSAGE);
        }              
    }//GEN-LAST:event_categorySearchButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        this.dispose();       //closes the information system.
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        //Opens any file from Desktop interface.
        JFileChooser filechooser = new JFileChooser();
        int i = filechooser.showOpenDialog(this);
            if(i == JFileChooser.APPROVE_OPTION) 
            {
                File file = filechooser.getSelectedFile();
                    //Opening file
                    //Checks if desktop interaction is available or not from this platform.
                    if(Desktop.isDesktopSupported()) 
                    {
                        try
                        {      
                        File openFile = new File(file.getAbsolutePath());
                        Desktop.getDesktop().open(openFile);  //opens the absolute form of this abstract pathname.
                        }
                        catch (IOException iOException)
                        {
                            //Showing the path in a dialog box.
                        JOptionPane.showMessageDialog(this, "No application available to open the file you chose.\n"
                                + "Chosen File location: \n" + file.getAbsolutePath(), "Error!", JOptionPane.PLAIN_MESSAGE);
                        }
                        catch(Exception filenfException) 
                        {
                            JOptionPane.showMessageDialog(this, "There was an error while accessing the file.\n", "Error!", JOptionPane.PLAIN_MESSAGE);
                        }
                    } 
                    else
                    {
                         Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Desktop interaction was denied.", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }
            }
            else
            { 
                //If user doesn't select files and click exits in the file chooser dialog box.
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "No file was selected.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(this, "Car Accessories Information System version 1.0 \n"
                +"Developed by: \n"
                +"1. Kushal Gurung \n"
                +"2. Sanjit Adhikari \n"
                +"3. Sadikshya Baral \n"
                +"4. Sagar Nepali \n"
                +"5. Hrithik Sunar"
                , "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void viewHelpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHelpMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Learn to use Car Accessories Information System: \n"
        +"1. To add new accessories items, fill all the text fields, select category, range level and recommendations. Then, click on (Add) Button. \n"
        +"2. To seach accessory of a particular price, enter price amount and click on (Search accessories) button. \n"
        +"3. To search accessories of a particular category, select the category option and then click on (Accessories available in category) button. \n"
        +"4. To open any file from Car Accessories Information System, press Ctrl+O or select (Open) menu item from (File) menu. \n"    
        +"5. To clear all the previously entered values in the text fields, click on (Clear) button. \n"   
        +"6. To know about the group members(developers) of this information system, press Alt+A or select (About) menu item from (Help) menu. \n"
        +"7. To remove a selected accessory details in the table, select a accessory in the table and then click on (Clear Selected) button. \n"
        +"8. To remove all the accessories details in the table, click on (Clear all) button. \n"        
        +"9. To close the application, click on (Exit) button or press Ctrl+E button. You can also exit by selecting (Exit) menu item of (File) menu.",
         "Help", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_viewHelpMenuItemActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        //It clears the values entered in text fields and the values selected in check boxes and radio button.
        accessoriesNameTextField.setText("");
        accessoriesNumberTextField.setText("");
        priceTextField.setText("");
        buttonGroup1.clearSelection();
        companyCheckBox.setSelected(false);
        communityCheckBox.setSelected(false);
        noRecommendationCheckBox.setSelected(false);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void priceSearchClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSearchClearButtonActionPerformed
        // TODO add your handling code here:
        //Clears the price entered by user.
       priceSearchTextField.setText("");
    }//GEN-LAST:event_priceSearchClearButtonActionPerformed

    private void clearSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSelectedButtonActionPerformed
        // TODO add your handling code here:
        //Removes the selected accessories item from the table.
        int [] rows = jTable1.getSelectedRows();
        for(int i=0; i<rows.length; i++)
        {
            model.removeRow(rows[i]);
        }
        JOptionPane.showMessageDialog(this, "Selected row has been deleted.", "Result", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_clearSelectedButtonActionPerformed

    private void accessoriesNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessoriesNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accessoriesNumberTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void accessoriesNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accessoriesNameTextFieldKeyTyped
        // TODO add your handling code here:
        //This method will not allow to enter integer value in accessories name.
        char obj = evt.getKeyChar();
        if(!(Character.isAlphabetic(obj))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_accessoriesNameTextFieldKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new CAD_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField accessoriesNameTextField;
    private javax.swing.JTextField accessoriesNumberTextField;
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JButton categorySearchButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearSelectedButton;
    private javax.swing.JCheckBox communityCheckBox;
    private javax.swing.JCheckBox companyCheckBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JRadioButton highRadioButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton lowRadioButton;
    private javax.swing.JRadioButton mediumRadioButton;
    private javax.swing.JCheckBox noRecommendationCheckBox;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton priceSearchButton;
    private javax.swing.JButton priceSearchClearButton;
    private javax.swing.JTextField priceSearchTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JMenuItem viewHelpMenuItem;
    // End of variables declaration//GEN-END:variables
}
